### ISSUE TITLE
fab deploy gives "AssertionError: Incorrectly configured!"

### ISSUE THREAD

**Issue by evets007** [andresriancho/nimbostratus-target#2]
Hey guys, I'm trying to setup a target for nimbostratus. I have boto configured with credentials, I keep receiving this error.
```
root@mrr0b0t:~/nimbostratus-target# fab deploy
Launching Django frontend instance
Removing IAM instance profile "django_frontend_nimbostratus"
Waiting for role django_frontend_nimbostratus to be available...
Waiting for instance to start...
Waiting for instance to start...
Checking if instance was correctly configured (this usually takes 5min)
Instance did not boot yet...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/root/nimbostratus-target/fabfile.py", line 19, in deploy
    deploy_django_frontend()
  File "/root/nimbostratus-target/servers/django_frontend/deploy.py", line 64, in deploy_django_frontend
    assert 'python-requests' in response.text, 'Incorrectly configured!'
AssertionError: Incorrectly configured!

```
Can anybody please help me out here?
Thanks! - Steve

**Comment by andresriancho** [comment]
Hmmm....

What happens if you change [this line](https://github.com/andresriancho/nimbostratus-target/blob/73b1ff96560898df62eff4d1b78ba8e926f784dc/servers/django_frontend/deploy.py#L64) to something like:

```python
assert 'python-requests' in response.text, 'Incorrectly configured! Response: %s' % response.text
```

**Comment by evets007** [comment]
Hey @andresriancho , updated that line and this is the output now,

```python
assert 'python-requests' in response.text, 'Incorrectly configured! Response: %s' % response.text
```

```
AssertionError: Incorrectly configured! Response: <h1>uWSGI Error</h1>Python application not found
```

**Comment by andresriancho** [comment]
When the EC2 instance boots it will run [this script](https://github.com/andresriancho/nimbostratus-target/blob/73b1ff96560898df62eff4d1b78ba8e926f784dc/servers/django_frontend/user_data.py)

It seems that something in the script is wrong, and the django application isn't even starting.

Login to the EC2 instance and take a look at `/var/log/cloud-user-data.log` (referenced [here](https://github.com/andresriancho/nimbostratus-target/blob/73b1ff96560898df62eff4d1b78ba8e926f784dc/servers/django_frontend/user_data.py#L14))

Since the script was written and tested ~3 years ago, the pypi package names might have changed, might have new dependencies which are failing to install, have new configuration parameters, etc.
